services:
  - type: web
    name: ai-interview-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: starter

  - type: web
    name: ai-interview-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://ai-interview-backend.onrender.com
    plan: starter 